services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi"
    postdeploy: |
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput

