services:
  - type: web
    name: backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    preDeployCommand: |
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py shell -c "
from django.contrib.auth import get_user_model
User = get_user_model()
if not User.objects.filter(email='shams@gmail.com').exists():
    User.objects.create_superuser(
        email='shams@gmail.com',
        password='12345',
        name='shams',
        tc=True,
        phone='03339853616',
        is_staff=True,
        is_superuser=True
    )
"
