# Generated by Django 4.2.25 on 2025-11-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='postal_code',
            new_name='postalcode',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='region',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
