# Generated by Django 5.1.2 on 2025-10-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0002_customerpoints_qrscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoints',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
