# Generated by Django 4.2.25 on 2025-11-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchants_App', '0004_tier_useractivity_userpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='outlet_image',
            field=models.ImageField(blank=True, help_text='Upload an image or provide an image URL.', null=True, upload_to='outlets/images/'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='outlet_image_url',
            field=models.URLField(blank=True, help_text='Alternatively, provide an image URL if no file is uploaded.', max_length=500, null=True),
        ),
    ]
