# Generated by Django 4.2.25 on 2025-11-10 05:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Merchants_App', '0005_outlet_outlet_image_outlet_outlet_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code or QR string for redemption', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coupon_images/'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coupon',
            name='terms_and_conditions_text',
            field=models.TextField(blank=True, help_text='Write full terms and conditions here as long text', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='points_required',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
