# Generated by Django 5.2.6 on 2025-09-20 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Merchants_App', '0003_coupon_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(help_text='Positive for points added, negative for redeemed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, help_text='Coupon redeemed in this transaction (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='Merchants_App.coupon')),
                ('merchant', models.ForeignKey(help_text='Merchant associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='Merchants_App.merchant')),
                ('outlet', models.ForeignKey(help_text='Specific outlet where the transaction occurred.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='Merchants_App.outlet')),
                ('user', models.ForeignKey(help_text='Customer who earns or redeems points.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
