# Generated by Django 4.2.25 on 2025-10-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchants_App', '0004_tier_useractivity_userpoints'),
        ('Loyalty_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='outlet',
            field=models.ForeignKey(blank=True, help_text='Specific outlet where the transaction occurred (nullable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='Merchants_App.outlet'),
        ),
    ]
